### ISSUE TITLE
Unable To Use LORE For Ingredient Items

### ISSUE THREAD

**Issue by Drag0nz69** [BenWoodworth/FastCraftPlus#32]
Remove these top lines, and replace all {brace-enclosed text}.

# Description
I am not sure if this is an error, a feature request, or I am just doing something wrong....

Several of the custom recipes we use on our server use custom drops as part of their ingredients. I am doing some more testing of your plugin and recent updates. Unfortunately, I can not get any recipe to work which  uses an item that has a custom LORE. The items we are using have a custom Name, Lore, and a standard Enchantment. I can set it to use the custom name with the enchantment. As long as I leave the lore off it works. As soon as I add the lore to the item it will not recognize it.

Here is an example Recipe:

```
 Draconian_Helm:
   type: shaped
   ingredients:
     a: ['minecraft:emerald', ANY, '{display:{Name:"§cDraconian §aEmerald",Lore:"Dragon Gem"},ench:[{id:20,lvl:1}]}']
     b: ['minecraft:leather_helmet']
   shape:
   - 'aaa'
   - 'aba'
   - 'aaa'
   result: [1, 'minecraft:leather_helmet', 0, '{display:{Color:1606152,Name:"§cDraconian §aEmerald Helm",Lore:"§cDraconian §aRelic"},ench:[{id:0,lvl:6},{id:34,lvl:3}]}']
```
