### ISSUE TITLE
Lore for result duplicated in ingredients section

### ISSUE THREAD

**Issue by RoboMWM** [BenWoodworth/FastCraftPlus#66]
# Description
Lore for resulting item has its lore duplicated in the ingredients section, oddly.
Version 0.22
http://i.imgur.com/yr9fYlf.png

Recipes.yml (yes I forgot to change the sample name):
```yml
wooden_pants:
 type: shaped
 ingredients:
   p: ['minecraft:iron_ingot', ANY]
 shape:
 - 'p p'
 - 'p p'
 result: [1, 'minecraft:iron_boots', 0, '{display:{Name:"Long Fall Boots",Lore:["You know what?","Go ahead and jump.","You''ve got braces on your legs."]}}']
```

Not sure if other stuff is needed, but could provide debug output and whatnot if required.

Also a question while I'm here, is it possible to simply replace existing item's names/lore? As per the example above, I want all iron boots to be named "Long Fall Boots," regardless if they're crafted via normal crafting table or fastcraft+. If I put the recipe for normal boots without fastcraft+, it will show just iron_boots. I suppose I can at least get rid of the extra iron boots in fastcraft+ via blacklist.yml, but that won't change anything for the normal crafting interface if I'm reading the blacklist.yml comments correctly.
