### ISSUE TITLE
Polish (PL) Translation

### ISSUE THREAD

**Issue by TheoMarque** [BenWoodworth/FastCraftPlus#90]
```
# If you translate this file, feel free to PM it to Kepler_ on spigotmc.org
# if you would like it to be officially added to FastCraft+ officially.
#
# Use ampersands (&) for formatting/color codes. Info about formatting codes:
# http://minecraft.gamepedia.com/Formatting_codes

gui:
  title: 'FastCraft+'

  # Leave blank to keep item names unchanged.
  item-name: # Variables: name

  hashcode: # Variables: hash
  - '&7Hashcode:'
  - '&7 <hash>'

  ingredients:
    label: '&aSkladniki:'
    item: '&a <amount>x <item>' # Variables: amount, item

  results:
    label: '&aProdukty:'
    item: '&a <amount>x <item>' # Variables: amount, item

  toolbar:
    page-prev:
      title: '&aPoprzednia strona'
      description: # Variables: prev, total, cur
      - '&bIdz do strony <prev>/<total>'

    page-next:
      title: '&aNastepna strona'
      description: # Variables: prev, total, cur
      - '&bIdz do strony <next>/<total>'

    craft-items:
      title: '&aStworz przedmioty'
      description:
      - '&bStworz przedmioty'

    craft-armor:
      title: '&aStworz barwiona skorzana zbroje'
      description:
      - '&bStworz barwiona skorzana zbroje'

    craft-fireworks:
      title: '&aStworz fajerwerk'
      description:
      - '&bStworz fajerwerki'

    refresh:
      title: '&aOdswiez'
      description:
      - '&bOdswiez interfejs FastCraft+'

    multiplier:
      title: '&aMnoznik tworzenia (<mult>x)' # Variables: mult
      description: # Variables: mult
      - '&bLewy/prawy przycisk myszy by zwiekszyc/zmniejszyc'
      - '&bZ SHIFT rosnie o 1'
      - '&bSrodkowy mnozy o 1'

    workbench:
      title: '&aStol rzemieslniczy'
      description:
      - '&bOtworz zwykly stol rzemieslniczy (3x3)'
      - '&bUzyj &a/fc toggle&b by wylaczyc FastCraft+'

commands:
  usage: '&cUzycie polecenia: <usage>' # Variables: usage
  no-perm: '&cNie masz uprawnien aby uzyc polecenia, potrzebne uprawnienia: <perm>' # Variables: perm
  player-only: '&cMusisz byc graczem aby uzyc tego polecenia'
  console-only: '&cPolecenie dostepne tylko z konsoli'
  unknown-player: '&cNieznany gracz: <player>' # Variables: player

  fastcraft toggle:
    output:
      on-self:   '&aInterfejs FastCraft+ aktywny.'
      off-self:  '&aInterfejs FastCraft+ nieaktywny.'
      on-other:  '&aInterfejs FastCraft+ aktywny dla gracza <player>.'  # Variables: player
      off-other: '&aInterfejs FastCraft+ nieaktywny dla gracza <player>.' # Variables: player

  fastcraftadmin reload:
    output: '&aFastCraft+ - konfiguracja przeladowana.'

# The localized names of items.
# d: Default item name.
# number: Name for specific item data.
items:
#  'minecraft:diamond': 'Diamond'
#  'minecraft:planks':
#    d: 'Wood Planks'
#    0: 'Oak Wood Planks'
#    1: 'Spruce Wood Planks'
#    2: 'Birch Wood Planks'
#    3: 'Jungle Wood Planks'
#    4: 'Acacia Wood Planks'
#    5: 'Dark Oak Wood Planks'
```
